config/routes.rb
Tasklist::Application.routes.draw do

  resources :lists do
    resources :tasks do
      member do
        post :complete
        post :uncomplete
      end
    end

    member do
      get :share_link
      post :copy_and_paste
    end
    collection do
      post :change_tag
    end
  end

  get '/share/:uuid' => 'shares#create'
  get '/copies/:id' => 'lists#copies', as: :copies

  resources :shares, only: [:create, :new]

  get "/auth/:provider/callback" => "sessions#create"
  get "/login" => "sessions#login"
  get "/logout" => "sessions#destroy", :as => :logout

  root 'sessions#login'

end

app/models/list.rb
class List
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Taggable

  before_save :generate_uuid

  field :name, type: String
  field :description, type: String
  field :uuid, type: String
  field :completed, type: Mongoid::Boolean, default: false

  validates_presence_of :name

  belongs_to :user
  belongs_to :original, class_name: "#{self.name}", inverse_of: :copies
  has_many :shares
  has_many :tasks
  has_many :copies, class_name: "#{self.name}", inverse_of: :original

  default_scope -> {order_by(created_at: :desc)}

  def copied_list(user)
    new_list = self.class.create(copy_attributes) do |new_list|
      new_list.original = self
      new_list.user = user
      new_list.name = "copy of (#{name})"
    end

    copy_tasks(new_list)
    new_list
  end

  def list_completed
    self.completed = !tasks.where(completion: false).any?
  end

  private
  def copy_tasks(new_list)
    tasks.each do |task|
      task.get_and_copy_task(new_list.id)
    end
  end

  def copy_attributes
    attributes.slice('name', 'description')
  end

  def generate_uuid
    self.uuid ||= SecureRandom.uuid
  end
end

app/models/share.rb
class Share
  include Mongoid::Document
  belongs_to :user
  belongs_to :list
end

app/models/task.rb
class Task
  include Mongoid::Document
  include Mongoid::Timestamps

  after_save :check_list_completed
  after_destroy :check_list_completed

  field :completion, type: Mongoid::Boolean, default: false
  field :description, type: String

  belongs_to :list

  validates_presence_of :description

  def get_and_copy_task(id_list)
    Task.create(attributes.slice('completion', 'description').merge(list_id: id_list))
  end

  def check_list_completed
    list.list_completed
    list.save if list.changed?
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  field :name, type: String
  field :email, type: String
  field :uid, type: String

  has_many :lists
  has_many :shares

  def all_lists
    shared = shared_lists.concat(self.lists)
  end

  def all_lists_tagged(tag_list)
    all_lists.select { |list| !(list.tags_array & tag_list).empty? }
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.email = auth["info"]["email"]
    end
  end

  private

    def shared_lists
      Share.where( user_id: self.id ).map { |share| share.list }
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :login_required
  helper_method :logged_in?, :current_user
  expose(:auth_path) { "/auth/google_oauth2" }

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end

  private

  def login_required
    redirect_to login_path unless logged_in?
  end

  def logged_in?
    current_user.present?
  end

  def current_user
    return @current_user if defined?(@current_user)
    @current_user ||= begin
      if session[:user_id] && (user = User.find_by(id: session[:user_id]))
        user
      end
    end
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  respond_to(:html)

  expose(:list_to_copy) { List.find(params[:id])}
  expose_decorated(:lists) { get_lists }
  expose_decorated(:list) { find_or_create_list }
  expose(:tags) { List.tags_with_weight }
  expose_decorated(:tasks) { list.tasks.decorate }
  expose_decorated(:task) { list.tasks.build }
  expose(:new_list) { list_to_copy.copied_list(current_user) }

  # GET /lists
  def index
  end

  # GET /lists/1
  def show
  end

  # GET /lists/new
  def new
    list.user = current_user
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  def create
    if list.save
      flash[:notice] = "List was successfully created."
    else
      flash[:alert] = "There was an error!"
    end
    respond_with(list)
  end

  # PATCH/PUT /lists/1
  def update
    if list.save
      flash[:notice] = "List was successfully updated."
    else
      flash[:alert] = "There was an error!"
    end
    respond_with(list)
  end

  # DELETE /lists/1
  def destroy
    if list.destroy
      flash[:notice] = "List was successfully destroyed."
    else
      flash[:alert] = "There was an error!"
    end
    redirect_to lists_path
  end

  def copy_and_paste
    if new_list.persisted?
      flash[:notice] = "List was successfully copied."
    else
      flash[:alert] = "There was an error!"
    end
    redirect_to new_list
  end

  def share_link
    url = "#{ root_url }shares/new?uuid=#{ list.uuid }"
    respond_to do |format|
      format.json { render :json => {:url => url } }
    end
  end

  def change_tag
    session[:active_tags] ||= []
    active_tags = session[:active_tags]
    tag_id = params[:tag_id]
    if tag_id
      if active_tags.include? tag_id
        active_tags.delete tag_id
      else
        session[:active_tags].push(params[:tag_id])
      end
    end
    session[:active_tags] = active_tags
    redirect_to lists_path
  end

  def copies
  end

  private
    def find_or_create_list
      list =
      if params[:id].present?
        List.find(params[:id])
      else
        current_user.lists.build
      end
      list.assign_attributes(list_params) if params[:list].present?
      list
    end

    def list_params
      params.require(:list).permit(:name, :description, :tags)
    end

    def get_lists
      active_tags = session[:active_tags]
      if active_tags and not active_tags.empty?
        current_user.all_lists_tagged(active_tags)
      else
        current_user.all_lists
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :login_required, :only => [:create, :login]
  def create
    auth = request.env["omniauth.auth"]
    user = begin
      User.find_by(uid: auth["uid"])
    rescue Mongoid::Errors::DocumentNotFound
      User.create_with_omniauth(auth)
    end

    session[:user_id] = user.id
    redirect_to root_url, :notice => "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end

  def login
    redirect_to lists_path if logged_in?
  end
end

app/controllers/shares_controller.rb
class SharesController < ApplicationController
  expose(:uuid) { params[:uuid] }
  expose(:list) { List.find_by(uuid: params[:uuid]) }
  def create
    unless current_user.all_lists.include? list
      Share.create user: current_user, list: list
    end
    redirect_to list
  end

  def new
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  expose(:list) { current_user.lists.find(params[:list_id]) }
  expose(:tasks) { list.tasks }
  expose_decorated(:task, attributes: :task_params)

  def index
  end

  def new
  end

  def create
    if task.save
      respond_to do |format|
        format.html { redirect_to list }
        format.js
      end
      
    else
      render :new
    end
  end

  def update
    if task.save
      redirect_to task.list, notice: 'Task was successfully updated to the list'
    else
      render :edit
    end
  end

  def edit
  end

  def destroy
    task.destroy
    redirect_to task.list, notice: 'Task was successfully deleted'
  end

  def show
  end

  def complete
    task = Task.find(params[:id])
    task.update_attributes(completion: true)
    redirect_to task.list, notice: 'Task marked as completed'
  end

  def uncomplete
    task = Task.find(params[:id])
    task.update_attributes(completion: false)
    redirect_to task.list, notice: 'Task marked as not completed'
  end

  private

    def task_params
      params.require(:task).permit(:completion, :description)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
  def tag_class (tag)
    if session[:active_tags] and session[:active_tags].include? tag[0]
      "active_tag"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper

end

app/views/layouts/_errors.html.haml
- if object.errors.any?
  #error_explanation
    %h2= "#{pluralize(object.errors.count, "error")} prohibited this element from being saved:"
    %ul
      - object.errors.full_messages.each do |msg|
        %li= msg

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_top_bar.html.haml
%nav.navbar.navbar-inverse.top-bar
  .container
    .navbar-header
      = link_to 'List it!', root_path, class: 'navbar-brand'
    %ul.nav.navbar-nav.navbar-right
      - if logged_in?
        %li.navbar-text
          .user-name= current_user.name
        %li
          = link_to "Log out", logout_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tasklist</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Tasklist
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = render "layouts/top_bar"
    .container
      .row
        .span12
          = render 'layouts/messages'
      -if content_for?(:page_title)
        .row
          .page-title.col-md-12= yield(:page_title)
      = yield

app/views/lists/_form.html.haml
.form-horizontal
  = form_for list do |f|
    = render 'layouts/errors', object: list
    %div.form-group
      = f.label :name, {class: "col-sm-2 control-label"}
      %div.col-sm-10
        = f.text_field :name, {class: "form-control"}
    %div.form-group
      = f.label :description, {class: "col-sm-2 control-label"}
      %div.col-sm-10
        = f.text_field :description, {class: "form-control"}
    %div.form-group
      = f.label :tags, {class: "col-sm-2 control-label"}
      %div.col-sm-10
        = f.text_field :tags, {class: "form-control"}
    %div.form-group
      %div.col-sm-offset-2.col-sm-10
        = f.submit 'Save', {class: "btn btn-default"}

app/views/lists/_list_short.haml
%div{class: "#{list.list_completed_class}"}
  %h1.list-elem-title= list.name
  %p.list-elem-description= list.description

  = link_to 'Show', list, class: 'btn btn-primary btn-xs'
  = link_to 'Edit', edit_list_path(list), class: 'btn btn-primary btn-xs'
  = link_to 'Destroy', list, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-primary btn-xs'
  = link_to 'Share', "#", :data => { :list_id => list.id.to_str }, class: 'btn btn-primary btn-xs'

app/views/lists/_share_popup.html.haml
%div#popup.hidden
  %span.close_button
  %span.msg
    %span.msg_body You can share your list using this link:
    %span#link.link
  %button#clipboard_btn{ data: { clipboard_target: 'link' } } Click me to copy the link

app/views/lists/_tag_cloud.haml
- tags.each do |tag|
  %span.label
    = "#{tag[0]} (#{tag[1].to_i})"

app/views/lists/_tag_cloud.html.haml
Tags:
- tags.each do |tag|
  %span.label.label-default{ class: tag_class(tag) }
    = link_to "#{tag[0]} (#{tag[1].to_i})", change_tag_lists_path(tag_id: tag[0]), method: :post

app/views/lists/copies.html.haml
%h1 
  = "Copies of list \"#{list.name}\""
%table
  %tr
    %th Name
    %th Description
    %th
    %th
    %th

  - list.copies.each do |list|
    %tr
      %td= list.name
      %td= list.description
      %td= link_to 'Show', list
      %td= link_to 'Edit', edit_list_path(list)
      %td= link_to 'Destroy', list, :method => :delete, :data => { :confirm => 'Are you sure?' }
      %td= link_to 'Share', "#", :data => { :list_id => list.id.to_str }

app/views/lists/edit.html.haml
%h1 Editing list

= render 'form'

= link_to 'Show', @list
\|
= link_to 'Back', lists_path

app/views/lists/index.html.haml
-provide :page_title, 'Your lists'
= render partial: "share_popup"
= render "tag_cloud"
%ul.list-group
- lists.each do |list|
  %li.list-group-item
    = render partial: 'lists/list_short', locals: { list: list }
.row
  .col-md-12= link_to 'New List', new_list_path, class: 'btn btn-primary btn-lg btn-block'

app/views/lists/new.html.haml
%h1 New list

= render 'form'



= link_to 'Back', lists_path

app/views/lists/show.html.haml
%h2.text-info
  = list.name.titleize
%h4.text-muted
  = list.description

%div.task.left.col-md-2
  %h4
    Tasks:
%div.task.right.col-md-10{id: 'tasks'}
  = render 'tasks/tasks'
%div.clear

%br
%div.task.left.col-md-2
  %h4
    Add new task:
%div.task.right.col-md-10   
  = render 'tasks/form'

%div.clear
= link_to 'Edit', edit_list_path(list)
\|
= link_to 'Back', lists_path
\|
= link_to "Copy list", copy_and_paste_list_path(list), method: :post
- if list.original.present?
  \|
  = link_to "Original list", list_path(list.original_id)
- if list.copies.present?
  \|
  = link_to "Copies of this list", copies_path(list)

app/views/shares/new.html.haml
%div.question_msg
  Do you want to add the list "#{list.name}" to your account?
%div.question_box
  =link_to "Yes", { action: "create", uuid: uuid }, class: "question_button"
  =link_to "No", { controller: "lists", action: "index" }, class: "question_button"

app/views/tasks/_form.html.haml
.form-horizontal
  = form_for [list, task], remote: task.new_record? do |f|
    = render 'layouts/errors', object: task
    %div.form-group.task
      %div.col-sm-12
        = f.text_field :description, {class: "form-control"}
    %div.form-group.task
      %div.col-sm-offset-2.col-sm-10
        = f.submit 'Save', {class: "btn btn-default"}

app/views/tasks/_task.html.haml
%div.task
  = button_to edit_list_task_path(list, task), method: :get, class: "btn btn-default btn-sm" do
    %span.glyphicon.glyphicon-edit
  = button_to list_task_path(list, task), method: :delete, class: "btn btn-default btn-sm" do
    %span.glyphicon.glyphicon-trash  
  - if task.completion
    = button_to uncomplete_list_task_path(list, task), class: "btn btn-default btn-sm" do
      %span.glyphicon.glyphicon-ok
  - else
    = button_to complete_list_task_path(list, task), class: "btn btn-default btn-sm" do
      %span.glyphicon.glyphicon-unchecked
  %span{class: "#{task.html_class}"}
    = task.description

app/views/tasks/_tasks.html.haml
- tasks.each do |task|
  = render task

app/views/tasks/edit.html.haml
%h2 Edit task
= render 'form', task: task

app/views/tasks/new.html.haml
%h2 New task
= render 'form'